version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: crud-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: crud-mongo
    volumes:
      - mongo_data:/data/db
  
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/crud-mongo

volumes:
  mongo_data: